export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_JOB_SUCCESS = "ADD_JOB_SUCCESS";
export const ADD_JOB_LOADING = "ADD_JOB_LOADING";
export const ADD_JOB_ERROR = "ADD_JOB_ERROR";

export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_LOADING = "DELETE_JOB_LOADING";
export const DELETE_JOB_ERROR = "DELETE_JOB_ERROR";

export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_LOADING = "EDIT_JOB_LOADING";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

export const FETCH_JOB_SUCCESS = "FETCH_JOB_SUCCESS";
export const FETCH_JOB_LOADING = "FETCH_JOB_LOADING";
export const FETCH_JOB_ERROR = "FETCH_JOB_ERROR";

export const FETCH_AllJOB_SUCCESS = "FETCH_AllJOB_SUCCESS";
export const FETCH_AllJOB_LOADING = "FETCH_AllJOB_LOADING";
export const FETCH_AllJOB_ERROR = "FETCH_AllJOB_ERROR";

export const FETCH_SINGLEJOB_SUCCESS = "FETCH_SINGLEJOB_SUCCESS";
export const FETCH_SINGLEJOB_LOADING = "FETCH_SINGLEJOB_LOADING";
export const FETCH_SINGLEJOB_ERROR = "FETCH_SINGLEJOB_ERROR";

export const SUBMIT_JOB_SUCCESS = "SUBMIT_JOB_SUCCESS";
export const SUBMIT_JOB_LOADING = "SUBMIT_JOB_LOADING";
export const SUBMIT_JOB_ERROR = "SUBMIT_JOB_ERROR";

export const FETCH_SUBMIT_JOB_SUCCESS = "FETCH_SUBMIT_JOB_SUCCESS";
export const FETCH_SUBMIT_JOB_LOADING = "FETCH_SUBMIT_JOB_LOADING";
export const FETCH_SUBMIT_JOB_ERROR = "FETCH_SUBMIT_JOB_ERROR";

export const FETCH_RECOM_JOB_SUCCESS = "FETCH_RECOM_JOB_SUCCESS";
export const FETCH_RECOM_JOB_LOADING = "FETCH_RECOM_JOB_LOADING";
export const FETCH_RECOM_JOB_ERROR = "FETCH_RECOM_JOB_ERROR";

export const FETCH_SIMILAR_JOB_SUCCESS = "FETCH_SIMILAR_JOB_SUCCESS";
export const FETCH_SIMILAR_JOB_LOADING = "FETCH_SIMILAR_JOB_LOADING";
export const FETCH_SIMILAR_JOB_ERROR = "FETCH_SIMILAR_JOB_ERROR";

export const FETCH_SUB_CAND_SUCCESS = "FETCH_SUB_CAND_SUCCESS";
export const FETCH_SUB_CAND_LOADING = "FETCH_SUB_CAND_LOADING";
export const FETCH_SUB_CAND_ERROR = "FETCH_SUB_CAND_ERROR";
