export const REGISTER_SUCCESS_HR_TEST = "Test_SUCCESS";
export const REGISTER_FAIL_HR_TEST = "Test_FAIL";
export const REGISTER_SUCCESS_HR_TEST_QUESTION = "Question_SUCCESS";

export const SET_MESSAGE_HR_TEST = "SET_MESSAGE";
export const CLEAR_MESSAGE_HR_TEST = "CLEAR_MESSAGE";
