export const REGISTER_SUCCESS_CANDIDATE = "REGISTER_SUCCESS";
export const REGISTER_FAIL_CANDIDATE = "REGISTER_FAIL";

export const SET_MESSAGE_CANDIDATE = "SET_MESSAGE";
export const CLEAR_MESSAGE_CANDIDATE = "CLEAR_MESSAGE";

export const CANDIDATE_FETCHING = "CANDIDATE_FETCHING";
export const CANDIDATE_SUCCESS = "CANDIDATE_SUCCESS";
export const CANDIDATE_FAILED = "CANDIDATE_FAILED";
export const CANDIDATE_CLEAR = "CANDIDATE_CLEAR";
