export const REGISTER_SUCCESS_CANDIDATE = "REGISTER_SUCCESS";
export const REGISTER_FAIL_CANDIDATE = "REGISTER_FAIL";
export const UPDATE_CANDIDATE = "UPDATE_CANDIDATE";
export const RETRIEVE_CANDIDATE = "RETRIEVE_CANDIDATE";
export const SET_MESSAGE_CANDIDATE = "SET_MESSAGE";
export const CLEAR_MESSAGE_CANDIDATE = "CLEAR_MESSAGE";
export const SET_CANDIDATE = "SET_CANDIDATE";
export const REMOVE_CANDIDATE = "REMOVE_CANDIDATE";

export const CANDIDATE_FETCHING = "CANDIDATE_FETCHING";
export const CANDIDATE_SUCCESS = "CANDIDATE_SUCCESS";
export const CANDIDATE_CLEAR = "CANDIDATE_CLEAR";
export const CANDIDATE_FAILED = "CANDIDATE_FAILED";