export const ADD_TEAM_SUCCESS = "ADD_TEAM_SUCCESS";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
export const EDIT_TEAM_SUCCESS = "EDIT_TEAM_SUCCESS";
export const FETCH_TEAM_SUCCESS = "FETCH_TEAM_SUCCESS";
